### ISSUE TITLE
What simulator do you use?

### ISSUE THREAD

**Issue by brunopinto900** [MiaoyanSun/MEAM620-Advanced-Robotics#1]
Hello Miaoyan,

I am studying quadrotor controls and motion planning. I found the MEAM620 course and wanted a python version instead of MATLAB. I found your code repository, but i noticed you don't have the code for the flightsim simulator. Is this part of the MEAM620 course?

If possible, can you send me the simulator code?

Thanks in advance.

**Comment by MiaoyanSun** [comment]
Dear Bruno,

Thank you for your email!

I found the flightsim code of MEAM620. Please refer to the attached file
and see if it works.

Hope you enjoy this course!! :D

Best regards,
Miaoyan

**Comment by MiaoyanSun** [comment]
hi~
